INSERT INTO GROUPE (nameGroupe) VALUES ('e1');
INSERT INTO GROUPE (nameGroupe) VALUES ('e2');
INSERT INTO GROUPE (nameGroupe) VALUES ('e3');
INSERT INTO GROUPE (nameGroupe) VALUES ('e4');
INSERT INTO GROUPE (nameGroupe) VALUES ('e5');
INSERT INTO GROUPE (nameGroupe) VALUES ('e6');
INSERT INTO GROUPE (nameGroupe) VALUES ('e7');
INSERT INTO GROUPE (nameGroupe) VALUES ('e8');